export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";


// for api type key 

export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL";
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST";


// for get video by id type 

export const WATCHSCREEN_VIDEOID_SUCCESS = "WATCHSCREEN_VIDEOID_SUCCESS";
export const WATCHSCREEN_VIDEOID_FAIL = "WATCHSCREEN_VIDEOID_FAIL";
export const WATCHSCREEN_VIDEOID_REQUEST = "WATCHSCREEN_VIDEOID_REQUEST";



