export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";


// for api type key 

export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL";
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST";


// for get video by id type 

export const WATCHSCREEN_VIDEOID_SUCCESS = "WATCHSCREEN_VIDEOID_SUCCESS";
export const WATCHSCREEN_VIDEOID_FAIL = "WATCHSCREEN_VIDEOID_FAIL";
export const WATCHSCREEN_VIDEOID_REQUEST = "WATCHSCREEN_VIDEOID_REQUEST";



// for get video by channel 
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS";
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL";
export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST";

export const COMMENT_DETAIL_REQUEST ="COMMENT_DETAIL_REQUEST";
export const COMMENT_DETAIL_SUCCESS ="COMMENT_DETAIL_SUCCESS";
export const COMMENT_DETAIL_FAIL ="COMMENT_DETAIL_FAIL";


export const CREATE_COMMENT_SUCCESS ="CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL ="CREATE_COMMENT_FAIL";

export const RELATED_VIDEOBY_ID_SUCCESS = "RELATED_VIDEOBY_ID_SUCCESS";
export const RELATED_VIDEOBY_ID_FAIL = "RELATED_VIDEOBY_ID_FAIL";
export const RELATED_VIDEOBY_ID_REQUEST = "RELATED_VIDEOBY_ID_REQUEST";


export const SEARCHED_VIDEOBY_SUCCESS = "SEARCHED_VIDEOBY_SUCCESS";
export const SEARCHED_VIDEOBY_FAIL = "SEARCHED_VIDEOBY_FAIL";
export const SEARCHED_VIDEOBY_REQUEST = "SEARCHED_VIDEOBY_REQUEST";



export const SET_SUBSCRIPTIONS_STATUS ="SET_SUBSCRIPTIONS_STATUS";